import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home({ restaurants }) {
  console.log(restaurants);
  return (
    <div className={styles.container}>
      <Head>
        <title>Strapi Demo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Hello World</h1>
      <h2>Strapi Demo</h2>
      {restaurants.map(restaurant => (
        <div key={restaurant.id}>
          <h1>{restaurant.name}</h1>
          <p>{restaurant.description}</p>
          <h2>{restaurant.isOpen}</h2>
          <img src={restaurant.img.url} alt='' />
        </div>
      ))}
    </div>
  );
}
export async function getServerSideProps() {
  const restaurants = await axios.get("http://localhost:1337/restaurants");

  return {
    props: {
      restaurants: restaurants.data,
    },
  };
}
